### ISSUE TITLE
[Enhancement] Material design light theme

### ISSUE THREAD

**Issue by XDrake99** [Birkbjo/OctoPrint-Themeify#1]
I created a theme for OctoPrint inspired to Material Design, this is the stylesheet:
```css
.btn {
	background: white;
	filter: brightness(1.0);
	border-radius: 3px;
}
.btn, .btn:focus, .btn:hover {
	transition: filter 0.2s ease, background-color 0.2s ease;
}
.btn.active, .btn.disabled, .btn:active, .btn:focus, .btn:hover, .btn[disabled] {
    filter: brightness(0.9);
}
.btn, .btn.active, .btn:active, .btn-group {
    box-shadow: 0 4px 6px -4px rgba(0, 0, 0, 0.47);
}
.btn-group .btn {
    box-shadow: none;
}
.dropdown-backdrop {
    display: none;
}
.btn-group>.btn+.dropdown-backdrop+.dropdown-toggle, .btn-group>.btn+.dropdown-toggle {
    padding-right: 8px;
	padding-left: 8px;
}
.progress {
	background: rgba(0, 0, 0, 0.07);
	box-shadow: none;
}
.progress .bar {
	background: #2196F3;
	box-shadow: none;
	border: 0;
}
.btn, .input-append .add-on, .input-prepend .add-on, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input, textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
    text-shadow: none;
    border: 1px solid rgba(0, 0, 0, 0.31);
}
.btn-primary, .btn-primary.active, .btn-primary.disabled, .btn-primary:active, .btn-primary:focus, .btn-primary:hover, .btn-primary[disabled] {
	color: #fff;
	background-color: #2196F3;
}
.btn-danger, .btn-danger.active, .btn-danger.disabled, .btn-danger:active, .btn-danger:focus, .btn-danger:hover, .btn-danger[disabled] {
	background-color: #F44336;
}
.btn-warning, .btn-warning.active, .btn-warning.disabled, .btn-warning:active, .btn-warning:focus, .btn-warning:hover, .btn-warning[disabled] {
	background-color: #FF9800;
}
.dropdown-menu li>a:hover, .dropdown-menu li>a:focus, .dropdown-submenu:hover>a {
	background: #2196F3;
}
.dropdown-menu {
	box-shadow: 0 5px 15px -5px rgba(0, 0, 0, 0.35);
	border: 1px solid rgba(0, 0, 0, 0.13);
	border-radius: 3px;
}
.accordion-group {
	border: 1px solid #e9e9e9;
    border-radius: 4px;
}
.tab-content {
	border-radius: 0 0 4px 4px;
}
.accordion-group, .tab-content {
	box-shadow: 0px 2px 5px -2px rgba(0, 0, 0, 0.32);
	background: white;
	margin-bottom: 10px;
}
textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
    background: white;
    box-shadow: none !important;
    border-color: #2196F3;
}
.slider .slider-track {
    box-shadow: none;
}
.slider .slider-selection {
	background: #2196F3;
	border: none;
	box-shadow: none;
}
.nav>li>a {
    color: inherit;
}
.legendColorBox > div {
   border-radius: 50%;
   padding: 0 !important;
   border: 0 !important;
}
.legendColorBox > div > div {
   border-radius: 50%;
   width: 0px !important;
   height: 0px !important;
   padding: 0 !important;
}
#navbar .navbar-inner {
	background-image: none !important;
	box-shadow: 0px 0px 15px black !important;
	border: none !important;
}
#navbar .navbar-inner .nav>li>a:hover {
    background: rgba(128, 128, 128, 0.5) !important;
}
#navbar .navbar-inner .brand, #navbar .navbar-inner .nav>li>a {
    text-shadow: none !important;
}
.navbar .brand {
    text-shadow: none !important;
}
#navbar .navbar-inner .nav>li.dropdown.active>.dropdown-toggle, #navbar .navbar-inner .nav>li.dropdown.open.active>.dropdown-toggle, #navbar .navbar-inner .nav>li.dropdown.open>.dropdown-toggle {
    background: rgba(255,255,255, 0.3) !important;
}
.modal.fade {
	box-shadow: 0 30px 50px -30px rgba(0, 0, 0, 0.76) !important;
	border: 0 !important;
}
.nav-list>.active>a, .nav-list>.active>a:hover {
	background-color: #2196F3;
}
.modal-footer {
	border: 0;
}
textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
	box-shadow: none;
}
.modal-backdrop, .modal-backdrop.fade.in {
	background: black;
}
#temperature-graph {
	background-image: none !important;
}
```
